if OS.mac?
	tap "homebrew/cask-fonts"
	tap "koekeishiya/formulae"

  # Work software
	tap "heroku/brew"
	brew "heroku"
  brew "firebase-cli"

	brew "trash"

	# Tiling WM - Yabai
	brew "yabai"
	brew "skhd"

	# Mac specific applications
	cask "scroll-reverser"

	cask "font-jetbrains-mono"
	cask "font-symbols-only-nerd-font"
	cask "bitwarden"
  cask "sleek"
end

tap "homebrew/bundle"

# Tools
brew "ripgrep"
brew "fzf"
brew "fd"
brew "git"
brew "git-filter-repo"
brew "tree"
brew "bat"
brew "htop"
brew "jq"
brew "neofetch"
brew "lazygit"
brew "eza"
brew "zoxide"
cask "nextcloud"
brew "watch"

# Languages and lang specific tooling
brew "fnm"
brew "python"

# Misc software
brew "nmap"
brew "mpv"

# Terminal config
cask "wezterm"
brew "fish"
brew "neovim", args: ["HEAD"]
brew "tmux"
