if OS.mac?
	tap "homebrew/cask-fonts"
	tap "koekeishiya/formulae"

	brew "trash"

	# Tiling WM - Yabai
	brew "yabai"
	brew "skhd"

	# Mac specific applications
	cask "scroll-reverser"

	cask "font-jetbrains-mono"
	cask "font-symbols-only-nerd-font"
end

tap "homebrew/bundle"

# Tools
brew "ripgrep"
brew "fzf"
brew "git"
brew "tree"
brew "bat"
brew "htop"
brew "jq"
brew "neofetch"
brew "lazygit"
brew "eza"

# Languages and lang specific tooling
brew "fnm"
brew "python"

# Misc software
brew "nmap"
brew "mpv"

# Terminal config
cask "wezterm"
brew "fish"
brew "neovim"
brew "tmux"
